[project]
name = "intersection-model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "lightning>=2.6.0",
    "matplotlib>=3.10.8",
    "opencv-python>=4.13.0.90",
    "pillow>=12.1.0",
    "python-dotenv>=1.2.1",
    "scikit-image>=0.26.0",
    "scipy>=1.17.0",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
    "wandb>=0.24.0",
]
